server:
  port: 80

#zuul:
#  ignoredServices: '*'
#  routes:
#    users: /myusers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:7461501b884a4e60a059d2fc43366677@localhost:8761/eureka/ 

spring: 
  application:
    name: api-gateway-1
  security: 
    basic: 
      enabled: false
