FROM openjdk:8-jdk-alpine
ARG JAR_FILE
VOLUME /app
EXPOSE 9099
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar", "--spring.profiles.active=prod"]